# -*- coding: utf-8 -*-
"""ExpenseTracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srOHNXYoRMEqUR5PBAO6meZsHr4qx8uC
"""

import sqlite3
from datetime import datetime

# Initialize SQLite database
conn = sqlite3.connect('finance_tracker.db')
c = conn.cursor()

# Create table if not exists
c.execute('''CREATE TABLE IF NOT EXISTS transactions
             (id INTEGER PRIMARY KEY AUTOINCREMENT,
              amount REAL,
              category TEXT,
              description TEXT,
              date TEXT)''')

class TextFinanceTracker:
    def __init__(self):
        pass

    def add_transaction(self, amount, category, description, date=None):
        if date is None:
            date = datetime.now().strftime('%Y-%m-%d')
        c.execute("INSERT INTO transactions (amount, category, description, date) VALUES (?, ?, ?, ?)",
                  (amount, category, description, date))
        conn.commit()

    def view_transactions(self):
        c.execute("SELECT * FROM transactions")
        transactions = c.fetchall()
        for transaction in transactions:
            print(f"ID: {transaction[0]}, Amount: {transaction[1]}, Category: {transaction[2]}, Description: {transaction[3]}, Date: {transaction[4]}")

    def calculate_summary(self):
        c.execute("SELECT category, SUM(amount) FROM transactions GROUP BY category")
        summary = c.fetchall()
        summary_str = "\nSummary:\n"
        for category, total in summary:
            summary_str += f"{category}: {total:.2f}\n"
        print(summary_str)

# Example usage
tracker = TextFinanceTracker()

# Function to interact with user
def main_menu():
    while True:
        print("\n======= Finance Tracker Menu =======")
        print("1. Add Transaction")
        print("2. View Transactions")
        print("3. Calculate Summary")
        print("4. Exit")
        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            amount = float(input("Enter amount: "))
            category = input("Enter category: ")
            description = input("Enter description: ")
            tracker.add_transaction(amount, category, description)
        elif choice == '2':
            print("\n======= Transactions List =======")
            tracker.view_transactions()
        elif choice == '3':
            tracker.calculate_summary()
        elif choice == '4':
            print("Exiting Finance Tracker...")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")

# Run the main menu
main_menu()

# Close database connection
conn.close()